# GOAP-Driven LLM API Specification
# Version: 1.0.0

openapi: 3.0.3
info:
  title: GOAP-Driven LLM API
  version: 1.0.0
  description: Goal-Oriented Action Planning API for LLM strategic reasoning

paths:
  /plan:
    post:
      summary: Generate and execute a GOAP plan
      operationId: generateAndExecutePlan
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PlanRequest"
      responses:
        "200":
          description: Plan executed successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlanResponse"
